// palavras.js — Lista Super-Expandida (Dicas de Uma Palavra)
// Definimos como propriedade global `window.WORDS` para compatibilidade
window.WORDS = [
  
  // --- Categoria: Festa ---
  {word: 'Festa na Praia', hint: 'Litoral', category: 'Festa'},
  {word: 'Balada', hint: 'Neon', category: 'Festa'},
  {word: 'Carnaval', hint: 'Blocos', category: 'Festa'},
  {word: 'Casamento', hint: 'Aliança', category: 'Festa'},
  {word: 'Aniversário', hint: 'Velas', category: 'Festa'},
  {word: 'Formatura', hint: 'Diploma', category: 'Festa'},
  {word: 'Churrasco', hint: 'Carvão', category: 'Festa'},
  {word: 'Show', hint: 'Palco', category: 'Festa'},
  {word: 'Festa Junina', hint: 'Quentão', category: 'Festa'},
  {word: 'Halloween', hint: 'Sustos', category: 'Festa'},
  {word: 'Natal', hint: 'Pinheiro', category: 'Festa'},
  {word: 'Réveillon', hint: 'Branco', category: 'Festa'},
  {word: 'Chá de Bebê', hint: 'Cegonha', category: 'Festa'},
  {word: 'Despedida de Solteiro', hint: 'Penas', category: 'Festa'},
  {word: 'Piquenique', hint: 'Manta', category: 'Festa'},
  {word: 'Festival de Música', hint: 'Multidão', category: 'Festa'},
  {word: 'Inauguração', hint: 'Fita', category: 'Festa'},
  {word: 'Karaokê', hint: 'Refrão', category: 'Festa'},
  {word: 'Bingo', hint: 'Cartela', category: 'Festa'},
  {word: 'Confraternização', hint: 'Brinde', category: 'Festa'},
  {word: 'Vaquinha', hint: 'Rateio', category: 'Festa'},
  {word: 'Festa do Pijama', hint: 'Travesseiro', category: 'Festa'},
  {word: 'Aniversário de Empresa', hint: 'Crachá', category: 'Festa'},
  {word: 'Festa à Fantasia', hint: 'Máscara', category: 'Festa'},
  {word: 'Boas-vindas', hint: 'Faixa', category: 'Festa'},
  {word: 'Festa Surpresa', hint: 'Esconderijo', category: 'Festa'},
  {word: 'Recepção de Casamento', hint: 'Buquê', category: 'Festa'},
  {word: 'Show de Talentos', hint: 'Júri', category: 'Festa'},
  {word: 'Comemoração de Gol', hint: 'Apito', category: 'Festa'},
  {word: 'Festa do Vizinho', hint: 'Som Alto', category: 'Festa'},

  // --- Categoria: Objetos ---
  {word: 'Esponja', hint: 'Porosa', category: 'Objetos'},
  {word: 'Elevador', hint: 'Vertical', category: 'Objetos'},
  {word: 'Guarda-Chuva', hint: 'Abrigo', category: 'Objetos'},
  {word: 'Relógio', hint: 'Tempo', category: 'Objetos'},
  {word: 'Controle Remoto', hint: 'Botões', category: 'Objetos'},
  {word: 'Semáforo', hint: 'Cores', category: 'Objetos'},
  {word: 'Escada', hint: 'Degraus', category: 'Objetos'},
  {word: 'Chave', hint: 'Fechadura', category: 'Objetos'},
  {word: 'Tesoura', hint: 'Corte', category: 'Objetos'},
  {word: 'Lâmpada', hint: 'Luz', category: 'Objetos'},
  {word: 'Cadeira', hint: 'Assento', category: 'Objetos'},
  {word: 'Garrafa', hint: 'Líquido', category: 'Objetos'},
  {word: 'Martelo', hint: 'Prego', category: 'Objetos'},
  {word: 'Óculos', hint: 'Lentes', category: 'Objetos'},
  {word: 'Bússola', hint: 'Norte', category: 'Objetos'},
  {word: 'Espelho', hint: 'Reflexo', category: 'Objetos'},
  {word: 'Ventilador', hint: 'Hélice', category: 'Objetos'},
  {word: 'Termômetro', hint: 'Febre', category: 'Objetos'},
  {word: 'Mochila', hint: 'Alças', category: 'Objetos'},
  {word: 'Pilha', hint: 'Energia', category: 'Objetos'},
  {word: 'Caneta', hint: 'Tinta', category: 'Objetos'},
  {word: 'Cadeado', hint: 'Segredo', category: 'Objetos'},
  {word: 'Binóculo', hint: 'Distância', category: 'Objetos'},
  {word: 'Vela', hint: 'Pavio', category: 'Objetos'},
  {word: 'Régua', hint: 'Medida', category: 'Objetos'},
  {word: 'Lanterna', hint: 'Apagão', category: 'Objetos'},
  {word: 'Liquidificador', hint: 'Lâmina', category: 'Objetos'},
  {word: 'Travesseiro', hint: 'Pena', category: 'Objetos'},
  {word: 'Despertador', hint: 'Soneca', category: 'Objetos'},
  {word: 'Extintor', hint: 'Espuma', category: 'Objetos'},
  {word: 'Agulha', hint: 'Costura', category: 'Objetos'},
  {word: 'Corda', hint: 'Nó', category: 'Objetos'},
  {word: 'Mala', hint: 'Rodinhas', category: 'Objetos'},
  {word: 'Guarda-Roupa', hint: 'Cabide', category: 'Objetos'},
  {word: 'Carteira', hint: 'Cédula', category: 'Objetos'},

  // --- Categoria: Comida ---
  {word: 'Pizza', hint: 'Fatia', category: 'Comida'},
  {word: 'Sushi', hint: 'Hashi', category: 'Comida'},
  {word: 'Café', hint: 'Manhã', category: 'Comida'},
  {word: 'Pipoca', hint: 'Salto', category: 'Comida'},
  {word: 'Lasanha', hint: 'Camadas', category: 'Comida'},
  {word: 'Chocolate', hint: 'Cacau', category: 'Comida'},
  {word: 'Hambúrguer', hint: 'Chapa', category: 'Comida'},
  {word: 'Pão', hint: 'Farinha', category: 'Comida'},
  {word: 'Sopa', hint: 'Colher', category: 'Comida'},
  {word: 'Macarrão', hint: 'Molho', category: 'Comida'},
  {word: 'Sorvete', hint: 'Gelado', category: 'Comida'},
  {word: 'Feijoada', hint: 'Quarta-feira', category: 'Comida'},
  {word: 'Queijo', hint: 'Rato', category: 'Comida'},
  {word: 'Salada', hint: 'Verde', category: 'Comida'},
  {word: 'Ovo', hint: 'Gema', category: 'Comida'},
  {word: 'Brigadeiro', hint: 'Granulado', category: 'Comida'},
  {word: 'Tapioca', hint: 'Goma', category: 'Comida'},
  {word: 'Coxinha', hint: 'Desfiado', category: 'Comida'},
  {word: 'Churros', hint: 'Canela', category: 'Comida'},
  {word: 'Yakisoba', hint: 'Wok', category: 'Comida'},
  {word: 'Risoto', hint: 'Cremoso', category: 'Comida'},
  {word: 'Tacos', hint: 'Tortilha', category: 'Comida'},
  {word: 'Waffle', hint: 'Xadrez', category: 'Comida'},
  {word: 'Pudim', hint: 'Caramelo', category: 'Comida'},
  {word: 'Pão de Queijo', hint: 'Polvilho', category: 'Comida'},
  {word: 'Açaí', hint: 'Roxo', category: 'Comida'},
  {word: 'Mandioca', hint: 'Raiz', category: 'Comida'},
  {word: 'Vinho', hint: 'Uva', category: 'Comida'},
  {word: 'Croissant', hint: 'Lua', category: 'Comida'},
  {word: 'Sanduíche', hint: 'Recheio', category: 'Comida'},
  {word: 'Bolo', hint: 'Cobertura', category: 'Comida'},
  {word: 'Picanha', hint: 'Brasa', category: 'Comida'},
  {word: 'Marshmallow', hint: 'Fogueira', category: 'Comida'},
  {word: 'Sashimi', hint: 'Crudo', category: 'Comida'},

  // --- Categoria: Animais ---
  {word: 'Cachorro', hint: 'Lealdade', category: 'Animais'},
  {word: 'Gato', hint: 'Independente', category: 'Animais'},
  {word: 'Coruja', hint: 'Noite', category: 'Animais'},
  {word: 'Camelo', hint: 'Deserto', category: 'Animais'},
  {word: 'Tubarão', hint: 'Barbatana', category: 'Animais'},
  {word: 'Pinguim', hint: 'Gelo', category: 'Animais'},
  {word: 'Polvo', hint: 'Tinta', category: 'Animais'},
  {word: 'Leão', hint: 'Juba', category: 'Animais'},
  {word: 'Elefante', hint: 'Memória', category: 'Animais'},
  {word: 'Macaco', hint: 'Cipó', category: 'Animais'},
  {word: 'Cavalo', hint: 'Galope', category: 'Animais'},
  {word: 'Cobra', hint: 'Peçonha', category: 'Animais'},
  {word: 'Borboleta', hint: 'Metamorfose', category: 'Animais'},
  {word: 'Abelha', hint: 'Mel', category: 'Animais'},
  {word: 'Sapo', hint: 'Lagoa', category: 'Animais'},
  {word: 'Raposa', hint: 'Astúcia', category: 'Animais'},
  {word: 'Esquilo', hint: 'Bochecha', category: 'Animais'},
  {word: 'Girafa', hint: 'Pescoço', category: 'Animais'},
  {word: 'Rinoceronte', hint: 'Chifre', category: 'Animais'},
  {word: 'Lobo', hint: 'Alcateia', category: 'Animais'},
  {word: 'Urso', hint: 'Hibernação', category: 'Animais'},
  {word: 'Águia', hint: 'Garras', category: 'Animais'},
  {word: 'Tartaruga', hint: 'Casco', category: 'Animais'},
  {word: 'Canguru', hint: 'Bolsa', category: 'Animais'},
  {word: 'Morcego', hint: 'Eco', category: 'Animais'},
  {word: 'Zebra', hint: 'Listras', category: 'Animais'},
  {word: 'Jacaré', hint: 'Pântano', category: 'Animais'},
  {word: 'Avestruz', hint: 'Velocista', category: 'Animais'},
  {word: 'Camaleão', hint: 'Disfarce', category: 'Animais'},
  {word: 'Ouriço', hint: 'Espinho', category: 'Animais'},
  {word: 'Pavão', hint: 'Leque', category: 'Animais'},
  {word: 'Coala', hint: 'Eucalipto', category: 'Animais'},
  {word: 'Foca', hint: 'Aplauso', category: 'Animais'},
  {word: 'Joaninha', hint: 'Sorte', category: 'Animais'},
  {word: 'Formiga', hint: 'Colônia', category: 'Animais'},

  // --- Categoria: Lazer ---
  {word: 'Cinema', hint: 'Tela', category: 'Lazer'},
  {word: 'Praia', hint: 'Ondas', category: 'Lazer'},
  {word: 'Videogame', hint: 'Controle', category: 'Lazer'},
  {word: 'Livro', hint: 'Páginas', category: 'Lazer'},
  {word: 'Acampar', hint: 'Barraca', category: 'Lazer'},
  {word: 'Pescaria', hint: 'Isca', category: 'Lazer'},
  {word: 'Dança', hint: 'Ritmo', category: 'Lazer'},
  {word: 'Teatro', hint: 'Atos', category: 'Lazer'},
  {word: 'Viagem', hint: 'Malas', category: 'Lazer'},
  {word: 'Parque', hint: 'Balanço', category: 'Lazer'},
  {word: 'Esporte', hint: 'Competição', category: 'Lazer'},
  {word: 'Piscina', hint: 'Cloro', category: 'Lazer'},
  {word: 'Surfe', hint: 'Prancha', category: 'Lazer'},
  {word: 'Yoga', hint: 'Tapete', category: 'Lazer'},
  {word: 'Maratona de Séries', hint: 'Sofá', category: 'Lazer'},
  {word: 'Jardinagem', hint: 'Vaso', category: 'Lazer'},
  {word: 'Pintura', hint: 'Pincel', category: 'Lazer'},
  {word: 'Fotografia', hint: 'Lente', category: 'Lazer'},
  {word: 'Caminhada', hint: 'Trilha', category: 'Lazer'},
  {word: 'Patinação', hint: 'Rodas', category: 'Lazer'},
  {word: 'Pôquer', hint: 'Blefe', category: 'Lazer'},
  {word: 'Quebra-cabeça', hint: 'Peças', category: 'Lazer'},
  {word: 'Ciclismo', hint: 'Pedal', category: 'Lazer'},
  {word: 'Mergulho', hint: 'Snorkel', category: 'Lazer'},
  {word: 'Escalada', hint: 'Corda', category: 'Lazer'},
  {word: 'Sinuca', hint: 'Taco', category: 'Lazer'},
  {word: 'Boliche', hint: 'Pinos', category: 'Lazer'},
  {word: 'Origami', hint: 'Dobra', category: 'Lazer'},
  {word: 'Skate', hint: 'Manobra', category: 'Lazer'},
  {word: 'Cantar no Chuveiro', hint: 'Sabonete', category: 'Lazer'},

  // --- Categoria: Lugares ---
  {word: 'Praça', hint: 'Banco', category: 'Lugares'},
  {word: 'Hospital', hint: 'Cura', category: 'Lugares'},
  {word: 'Aeroporto', hint: 'Voo', category: 'Lugares'},
  {word: 'Biblioteca', hint: 'Silêncio', category: 'Lugares'},
  {word: 'Museu', hint: 'Passado', category: 'Lugares'},
  {word: 'Deserto', hint: 'Areia', category: 'Lugares'},
  {word: 'Escola', hint: 'Aula', category: 'Lugares'},
  {word: 'Restaurante', hint: 'Menu', category: 'Lugares'},
  {word: 'Igreja', hint: 'Fé', category: 'Lugares'},
  {word: 'Supermercado', hint: 'Carrinho', category: 'Lugares'},
  {word: 'Montanha', hint: 'Cume', category: 'Lugares'},
  {word: 'Floresta', hint: 'Árvores', category: 'Lugares'},
  {word: 'Ponte', hint: 'Travessia', category: 'Lugares'},
  {word: 'Cemitério', hint: 'Lápide', category: 'Lugares'},
  {word: 'Shopping', hint: 'Vitrine', category: 'Lugares'},
  {word: 'Estádio', hint: 'Arquibancada', category: 'Lugares'},
  {word: 'Zoológico', hint: 'Jaula', category: 'Lugares'},
  {word: 'Cachoeira', hint: 'Queda', category: 'Lugares'},
  {word: 'Vulcão', hint: 'Lava', category: 'Lugares'},
  {word: 'Ilha', hint: 'Cercada', category: 'Lugares'},
  {word: 'Farol', hint: 'Naufrágio', category: 'Lugares'},
  {word: 'Caverna', hint: 'Estalactite', category: 'Lugares'},
  {word: 'Estação de Trem', hint: 'Plataforma', category: 'Lugares'},
  {word: 'Delegacia', hint: 'Boletim', category: 'Lugares'},
  {word: 'Fazenda', hint: 'Trator', category: 'Lugares'},
  {word: 'Castelo', hint: 'Fosso', category: 'Lugares'},
  {word: 'Favela', hint: 'Beco', category: 'Lugares'},
  {word: 'Feira Livre', hint: 'Barraca', category: 'Lugares'},
  {word: 'Geladaria', hint: 'Casquinha', category: 'Lugares'},
  {word: 'Posto de Gasolina', hint: 'Bomba', category: 'Lugares'},
  {word: 'Academia', hint: 'Halteres', category: 'Lugares'},
  {word: 'Sala de Aula', hint: 'Carteira', category: 'Lugares'},

  // --- Categoria: Profissões (antes Celebridades) ---
  {word: 'Futebolista', hint: 'Chuteira', category: 'Profissões'},
  {word: 'Cantor', hint: 'Microfone', category: 'Profissões'},
  {word: 'Ator', hint: 'Papel', category: 'Profissões'},
  {word: 'Bombeiro', hint: 'Fogo', category: 'Profissões'},
  {word: 'Professor', hint: 'Lousa', category: 'Profissões'},
  {word: 'Médico', hint: 'Bisturi', category: 'Profissões'},
  {word: 'Astronauta', hint: 'Espaço', category: 'Profissões'},
  {word: 'Policial', hint: 'Algemas', category: 'Profissões'},
  {word: 'Advogado', hint: 'Lei', category: 'Profissões'},
  {word: 'Engenheiro', hint: 'Planta', category: 'Profissões'},
  {word: 'Jornalista', hint: 'Notícia', category: 'Profissões'},
  {word: 'Cozinheiro', hint: 'Panela', category: 'Profissões'},
  {word: 'Dentista', hint: 'Cárie', category: 'Profissões'},
  {word: 'Veterinário', hint: 'Patinha', category: 'Profissões'},
  {word: 'Piloto', hint: 'Cabine', category: 'Profissões'},
  {word: 'Mecânico', hint: 'Macaco', category: 'Profissões'},
  {word: 'Eletricista', hint: 'Fio', category: 'Profissões'},
  {word: 'Padeiro', hint: 'Forno', category: 'Profissões'},
  {word: 'Costureira', hint: 'Agulha', category: 'Profissões'},
  {word: 'Garçom', hint: 'Bandeja', category: 'Profissões'},
  {word: 'Fotógrafo', hint: 'Flash', category: 'Profissões'},
  {word: 'Marceneiro', hint: 'Serra', category: 'Profissões'},
  {word: 'Salva-vidas', hint: 'Apito', category: 'Profissões'},
  {word: 'Caminhoneiro', hint: 'Estrada', category: 'Profissões'},
  {word: 'Bibliotecário', hint: 'Catálogo', category: 'Profissões'},
  {word: 'Tradutor', hint: 'Idioma', category: 'Profissões'},
  {word: 'Faxineira', hint: 'Vassoura', category: 'Profissões'},
  {word: 'Segurança', hint: 'Rádio', category: 'Profissões'},
  {word: 'Apresentador', hint: 'Plateia', category: 'Profissões'},
  {word: 'Padre', hint: 'Batina', category: 'Profissões'},
  {word: 'Juiz', hint: 'Martelo', category: 'Profissões'},

  // --- Categoria: Filmes/Séries ---
  {word: 'Harry Potter', hint: 'Cicatriz', category: 'Filmes/Séries'},
  {word: 'Darth Vader', hint: 'Respiração', category: 'Filmes/Séries'},
  {word: 'Coringa', hint: 'Riso', category: 'Filmes/Séries'},
  {word: 'Matrix', hint: 'Pílula', category: 'Filmes/Séries'},
  {word: 'Titanic', hint: 'Iceberg', category: 'Filmes/Séries'},
  {word: 'O Rei Leão', hint: 'Savana', category: 'Filmes/Séries'},
  {word: 'Star Wars', hint: 'Força', category: 'Filmes/Séries'},
  {word: 'Vingadores', hint: 'Heróis', category: 'Filmes/Séries'},
  {word: 'De Volta Para o Futuro', hint: 'Tempo', category: 'Filmes/Séries'},
  {word: 'Jurassic Park', hint: 'Dinossauro', category: 'Filmes/Séries'},
  {word: 'Homem-Aranha', hint: 'Teia', category: 'Filmes/Séries'},
  {word: 'Stranger Things', hint: 'Invertido', category: 'Filmes/Séries'},
  {word: 'La Casa de Papel', hint: 'Máscara', category: 'Filmes/Séries'},
  {word: 'Frozen', hint: 'Degelo', category: 'Filmes/Séries'},
  {word: 'Shrek', hint: 'Pântano', category: 'Filmes/Séries'},
  {word: 'Toy Story', hint: 'Coleção', category: 'Filmes/Séries'},
  {word: 'Friends', hint: 'Café', category: 'Filmes/Séries'},
  {word: 'Breaking Bad', hint: 'Trailer', category: 'Filmes/Séries'},
  {word: 'Game of Thrones', hint: 'Trono', category: 'Filmes/Séries'},
  {word: 'Os Simpsons', hint: 'Amarelo', category: 'Filmes/Séries'},
  {word: 'Avatar', hint: 'Azul', category: 'Filmes/Séries'},
  {word: 'Pantera Negra', hint: 'Vibranium', category: 'Filmes/Séries'},
  {word: 'Wandinha', hint: 'Trança', category: 'Filmes/Séries'},
  {word: 'O Senhor dos Anéis', hint: 'Tesouro', category: 'Filmes/Séries'},
  {word: 'Moana', hint: 'Remo', category: 'Filmes/Séries'},
  {word: 'Velozes e Furiosos', hint: 'Família', category: 'Filmes/Séries'},
  {word: 'A Ilha das Flores', hint: 'Documentário', category: 'Filmes/Séries'},
  {word: 'Squid Game', hint: 'Boneca', category: 'Filmes/Séries'},
  {word: 'Pokémon', hint: 'Treinador', category: 'Filmes/Séries'},
  {word: 'Naruto', hint: 'Bandana', category: 'Filmes/Séries'},
  {word: 'Bob Esponja', hint: 'Recife', category: 'Filmes/Séries'},
  {word: 'Chaves', hint: 'Barril', category: 'Filmes/Séries'},

  // --- Categoria: Países ---
  {word: 'Brasil', hint: 'Samba', category: 'Países'},
  {word: 'Japão', hint: 'Nascente', category: 'Países'},
  {word: 'Egito', hint: 'Pirâmide', category: 'Países'},
  {word: 'Itália', hint: 'Bota', category: 'Países'},
  {word: 'Estados Unidos', hint: 'Hollywood', category: 'Países'},
  {word: 'França', hint: 'Torre', category: 'Países'},
  {word: 'China', hint: 'Muralha', category: 'Países'},
  {word: 'Rússia', hint: 'Frio', category: 'Países'},
  {word: 'Austrália', hint: 'Vermelho', category: 'Países'},
  {word: 'México', hint: 'Sombrero', category: 'Países'},
  {word: 'Índia', hint: 'Bollywood', category: 'Países'},
  {word: 'Argentina', hint: 'Tango', category: 'Países'},
  {word: 'Canadá', hint: 'Bordo', category: 'Países'},
  {word: 'Grécia', hint: 'Deuses', category: 'Países'},
  {word: 'Alemanha', hint: 'Cerveja', category: 'Países'},
  {word: 'Espanha', hint: 'Touro', category: 'Países'},
  {word: 'Portugal', hint: 'Bacalhau', category: 'Países'},
  {word: 'Holanda', hint: 'Moinho', category: 'Países'},
  {word: 'Suíça', hint: 'Neutro', category: 'Países'},
  {word: 'Coreia do Sul', hint: 'K-pop', category: 'Países'},
  {word: 'Turquia', hint: 'Especiarias', category: 'Países'},
  {word: 'Marrocos', hint: 'Tapetes', category: 'Países'},
  {word: 'Peru', hint: 'Inca', category: 'Países'},
  {word: 'Cuba', hint: 'Charuto', category: 'Países'},
  {word: 'Irlanda', hint: 'Trevo', category: 'Países'},
  {word: 'Inglaterra', hint: 'Chá', category: 'Países'},
  {word: 'Escócia', hint: 'Xadrez', category: 'Países'},
  {word: 'Suécia', hint: 'Aurora', category: 'Países'},
  {word: 'Noruega', hint: 'Fiorde', category: 'Países'},
  {word: 'Tailândia', hint: 'Templos', category: 'Países'},
  {word: 'Indonésia', hint: 'Arquipélago', category: 'Países'},
  {word: 'Colômbia', hint: 'Esmeralda', category: 'Países'},
  {word: 'Chile', hint: 'Vulcões', category: 'Países'},
  {word: 'Quênia', hint: 'Savana', category: 'Países'}
];