// palavras.js — Lista Super-Expandida (Dicas de Uma Palavra)
// Definimos como propriedade global `window.WORDS` para compatibilidade
window.WORDS = [
  
  // --- Categoria: Festa ---
  {word: 'Festa na Praia', hint: 'Litoral', category: 'Festa'},
  {word: 'Balada', hint: 'Neon', category: 'Festa'},
  {word: 'Carnaval', hint: 'Blocos', category: 'Festa'},
  {word: 'Casamento', hint: 'Aliança', category: 'Festa'},
  {word: 'Aniversário', hint: 'Velas', category: 'Festa'},
  {word: 'Formatura', hint: 'Diploma', category: 'Festa'},
  {word: 'Churrasco', hint: 'Carvão', category: 'Festa'},
  {word: 'Show', hint: 'Palco', category: 'Festa'},
  {word: 'Festa Junina', hint: 'Quentão', category: 'Festa'},
  {word: 'Halloween', hint: 'Sustos', category: 'Festa'},
  {word: 'Natal', hint: 'Pinheiro', category: 'Festa'},
  {word: 'Réveillon', hint: 'Branco', category: 'Festa'},

  // --- Categoria: Objetos ---
  {word: 'Esponja', hint: 'Porosa', category: 'Objetos'},
  {word: 'Elevador', hint: 'Vertical', category: 'Objetos'},
  {word: 'Guarda-Chuva', hint: 'Abrigo', category: 'Objetos'},
  {word: 'Relógio', hint: 'Tempo', category: 'Objetos'},
  {word: 'Controle Remoto', hint: 'Botões', category: 'Objetos'},
  {word: 'Semáforo', hint: 'Cores', category: 'Objetos'},
  {word: 'Escada', hint: 'Degraus', category: 'Objetos'},
  {word: 'Chave', hint: 'Fechadura', category: 'Objetos'},
  {word: 'Tesoura', hint: 'Corte', category: 'Objetos'},
  {word: 'Lâmpada', hint: 'Luz', category: 'Objetos'},
  {word: 'Cadeira', hint: 'Assento', category: 'Objetos'},
  {word: 'Garrafa', hint: 'Líquido', category: 'Objetos'},
  {word: 'Martelo', hint: 'Prego', category: 'Objetos'},
  {word: 'Óculos', hint: 'Lentes', category: 'Objetos'},
  {word: 'Bússola', hint: 'Norte', category: 'Objetos'},

  // --- Categoria: Comida ---
  {word: 'Pizza', hint: 'Fatia', category: 'Comida'},
  {word: 'Sushi', hint: 'Hashi', category: 'Comida'},
  {word: 'Café', hint: 'Manhã', category: 'Comida'},
  {word: 'Pipoca', hint: 'Salto', category: 'Comida'},
  {word: 'Lasanha', hint: 'Camadas', category: 'Comida'},
  {word: 'Chocolate', hint: 'Cacau', category: 'Comida'},
  {word: 'Hambúrguer', hint: 'Chapa', category: 'Comida'},
  {word: 'Pão', hint: 'Farinha', category: 'Comida'},
  {word: 'Sopa', hint: 'Colher', category: 'Comida'},
  {word: 'Macarrão', hint: 'Molho', category: 'Comida'},
  {word: 'Sorvete', hint: 'Gelado', category: 'Comida'},
  {word: 'Feijoada', hint: 'Quarta-feira', category: 'Comida'},
  {word: 'Queijo', hint: 'Rato', category: 'Comida'},
  {word: 'Salada', hint: 'Verde', category: 'Comida'},
  {word: 'Ovo', hint: 'Gema', category: 'Comida'},

  // --- Categoria: Animais ---
  {word: 'Cachorro', hint: 'Lealdade', category: 'Animais'},
  {word: 'Gato', hint: 'Independente', category: 'Animais'},
  {word: 'Coruja', hint: 'Noite', category: 'Animais'},
  {word: 'Camelo', hint: 'Deserto', category: 'Animais'},
  {word: 'Tubarão', hint: 'Barbatana', category: 'Animais'},
  {word: 'Pinguim', hint: 'Gelo', category: 'Animais'},
  {word: 'Polvo', hint: 'Tinta', category: 'Animais'},
  {word: 'Leão', hint: 'Juba', category: 'Animais'},
  {word: 'Elefante', hint: 'Memória', category: 'Animais'},
  {word: 'Macaco', hint: 'Cipó', category: 'Animais'},
  {word: 'Cavalo', hint: 'Galope', category: 'Animais'},
  {word: 'Cobra', hint: 'Peçonha', category: 'Animais'},
  {word: 'Borboleta', hint: 'Metamorfose', category: 'Animais'},
  {word: 'Abelha', hint: 'Mel', category: 'Animais'},
  {word: 'Sapo', hint: 'Lagoa', category: 'Animais'},

  // --- Categoria: Lazer ---
  {word: 'Cinema', hint: 'Tela', category: 'Lazer'},
  {word: 'Praia', hint: 'Ondas', category: 'Lazer'},
  {word: 'Videogame', hint: 'Controle', category: 'Lazer'},
  {word: 'Livro', hint: 'Páginas', category: 'Lazer'},
  {word: 'Acampar', hint: 'Barraca', category: 'Lazer'},
  {word: 'Pescaria', hint: 'Isca', category: 'Lazer'},
  {word: 'Dança', hint: 'Ritmo', category: 'Lazer'},
  {word: 'Teatro', hint: 'Atos', category: 'Lazer'},
  {word: 'Viagem', hint: 'Malas', category: 'Lazer'},
  {word: 'Parque', hint: 'Balanço', category: 'Lazer'},
  {word: 'Esporte', hint: 'Competição', category: 'Lazer'},
  {word: 'Piscina', hint: 'Cloro', category: 'Lazer'},

  // --- Categoria: Lugares ---
  {word: 'Praça', hint: 'Banco', category: 'Lugares'},
  {word: 'Hospital', hint: 'Cura', category: 'Lugares'},
  {word: 'Aeroporto', hint: 'Voo', category: 'Lugares'},
  {word: 'Biblioteca', hint: 'Silêncio', category: 'Lugares'},
  {word: 'Museu', hint: 'Passado', category: 'Lugares'},
  {word: 'Deserto', hint: 'Areia', category: 'Lugares'},
  {word: 'Escola', hint: 'Aula', category: 'Lugares'},
  {word: 'Restaurante', hint: 'Menu', category: 'Lugares'},
  {word: 'Igreja', hint: 'Fé', category: 'Lugares'},
  {word: 'Supermercado', hint: 'Carrinho', category: 'Lugares'},
  {word: 'Montanha', hint: 'Cume', category: 'Lugares'},
  {word: 'Floresta', hint: 'Árvores', category: 'Lugares'},
  {word: 'Ponte', hint: 'Travessia', category: 'Lugares'},
  
  // --- Categoria: Profissões (antes Celebridades) ---
  {word: 'Futebolista', hint: 'Chuteira', category: 'Profissões'},
  {word: 'Cantor', hint: 'Microfone', category: 'Profissões'},
  {word: 'Ator', hint: 'Papel', category: 'Profissões'},
  {word: 'Bombeiro', hint: 'Fogo', category: 'Profissões'},
  {word: 'Professor', hint: 'Lousa', category: 'Profissões'},
  {word: 'Médico', hint: 'Bisturi', category: 'Profissões'},
  {word: 'Astronauta', hint: 'Espaço', category: 'Profissões'},
  {word: 'Policial', hint: 'Algemas', category: 'Profissões'},
  {word: 'Advogado', hint: 'Lei', category: 'Profissões'},
  {word: 'Engenheiro', hint: 'Planta', category: 'Profissões'},
  {word: 'Jornalista', hint: 'Notícia', category: 'Profissões'},
  {word: 'Cozinheiro', hint: 'Panela', category: 'Profissões'},

  // --- Categoria: Filmes/Séries ---
  {word: 'Harry Potter', hint: 'Cicatriz', category: 'Filmes/Séries'},
  {word: 'Darth Vader', hint: 'Respiração', category: 'Filmes/Séries'},
  {word: 'Coringa', hint: 'Riso', category: 'Filmes/Séries'},
  {word: 'Matrix', hint: 'Pílula', category: 'Filmes/Séries'},
  {word: 'Titanic', hint: 'Iceberg', category: 'Filmes/Séries'},
  {word: 'O Rei Leão', hint: 'Savana', category: 'Filmes/Séries'},
  {word: 'Star Wars', hint: 'Força', category: 'Filmes/Séries'},
  {word: 'Vingadores', hint: 'Heróis', category: 'Filmes/Séries'},
  {word: 'De Volta Para o Futuro', hint: 'Tempo', category: 'Filmes/Séries'},
  {word: 'Jurassic Park', hint: 'Dinossauro', category: 'Filmes/Séries'},
  {word: 'Homem-Aranha', hint: 'Teia', category: 'Filmes/Séries'},
  {word: 'Stranger Things', hint: 'Invertido', category: 'Filmes/Séries'},
  {word: 'La Casa de Papel', hint: 'Máscara', category: 'Filmes/Séries'},

  // --- Categoria: Países ---
  {word: 'Brasil', hint: 'Samba', category: 'Países'},
  {word: 'Japão', hint: 'Nascente', category: 'Países'},
  {word: 'Egito', hint: 'Pirâmide', category: 'Países'},
  {word: 'Itália', hint: 'Bota', category: 'Países'},
  {word: 'Estados Unidos', hint: 'Hollywood', category: 'Países'},
  {word: 'França', hint: 'Torre', category: 'Países'},
  {word: 'China', hint: 'Muralha', category: 'Países'},
  {word: 'Rússia', hint: 'Frio', category: 'Países'},
  {word: 'Austrália', hint: 'Canguru', category: 'Países'},
  //{word:Não, eu não sei. 'México', hint: 'Taco', category: 'Países'},
  {word: 'Índia', hint: 'Bollywood', category: 'Países'},
  {word: 'Argentina', hint: 'Tango', category: 'Países'},
  {word: 'Canadá', hint: 'Bordo', category: 'Países'},
  {word: 'Grécia', hint: 'Deuses', category: 'Países'}
];